### ISSUE TITLE
Strong references to inheritedAccessControlContext in java.lang.Thread cause classloader to be leaked

### ISSUE THREAD

**Issue by canyuan0801** [mjiderhamn/classloader-leak-prevention#147]
The application is written in java 8 and the app is run on `1.8.0_362,1.8.0_371`.

I use a custom classloader to hot load classes(let's call `script classes`), which are under the package `com.xxx.project1.script`

My custom classloader is:
```
public class ScriptClassLoader extends URLClassLoader {
    private String classPackage;
    private ClassLoader defaultClassLoader;
    private boolean dev;

    public static ScriptClassLoader newInstance(URL[] urls, String classPackage, boolean dev) {
        if (dev) {
            urls = ((URLClassLoader)ScriptClassLoader.class.getClassLoader()).getURLs();
        }

        return new ScriptClassLoader(urls, classPackage, dev);
    }

    protected ScriptClassLoader(URL[] urls, String classPackage, boolean dev) {
        super(urls);
        this.classPackage = classPackage;
        this.dev = dev;
        this.defaultClassLoader = ScriptClassLoader.class.getClassLoader();
    }

    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        if (!this.dev && name.startsWith(this.classPackage)) {
            Class<?> c = this.findLoadedClass(name);
            if (c == null) {
                c = this.findClass(name);
            } 

            if (resolve) {
                this.resolveClass(c);
            }

            return c;
        } else {
            return super.loadClass(name, resolve);
        }
    }
}
```

Recently I found after reload` script classes`, the original `script classes` didn't get unloaded. The reason is when creating a new thread, it will hold a new context object(see java.lang.Thread):
```
this.inheritedAccessControlContext =
                acc != null ? acc : AccessController.getContext();
```
So If a `script class` is created by such a thread, the object will hold the` ScriptClassLoader` object used to load the` script class`, causing this `ScriptClassLoader`  to be unable to be GC and thus unable to unload useless `script classes`.

The gc root straces:
```
com.xxx.engine.script.ScriptClassLoader
-classloader java.security.ProtectionDomain
--[4] java.security.ProtectionDomain[7]
---context java.security.AccessControlContext
----inheritedAccessControlContext java.lang.Thread
```

```
class com.xxx.project1.script.impl.AdvanceXXXScript
-java.lang.Object[160]
--elementData java.util.Vector
---classes com.xxx.engine.script.ScriptClassLoader
----classloader java.security.ProtectionDomain
-----[4]java.security.ProtectionDomain[7]
------context java.security.AccessControlContext
-------inheritedAccessControlContext java.lang.Thread
```
Since I'm not clear about the use of `inheritedAccessControlContext` and it cannot be accessed from external classes, the current solution is to initialize all core threads when creating the thread pool, avoiding thread creation triggered by `script classes`:
```
public static ScheduledExecutorService newScheduledThreadPool(int coreSize, String namePrefix) {
        ScheduledExecutorService service = Executors.newScheduledThreadPool(coreSize, new ThreadFactory() {
            final AtomicInteger n = new AtomicInteger();
            @Override
            public Thread newThread(Runnable r) {
                String name = namePrefix + "-" + n.incrementAndGet());
                return new Thread(r, name);
            }
        });
        ((ScheduledThreadPoolExecutor) service).prestartAllCoreThreads(); // initialize all core threads

        return service;
    }
```
But there are still some hidden dangers. Because Java only loads classes when they are in use. Therefore, in some places, even if static constants are written, it is still possible for script classes to trigger creation, such as:
```
abstract public class Http {
    private static final ScheduledExecutorService EXECUTOR = Executors.newScheduledThreadPool(16,
            new ThreadFactory() {
                private final AtomicInteger counter = new AtomicInteger(0);

                @Override
                public Thread newThread(Runnable r) {
                    return new Thread(r, "http-request-" + counter.incrementAndGet());
                }
            }
    );
```
If it is the first time using this class in a `script class`, then it will undoubtedly return to the above problem. The current solution is to proactively call these class/methods outside of the script during program startup to trigger their initialization, for example:
```
private static void envirInit() {
    Http.init();
    DBUpdateUtil.init();
}
```

Besides the above solution,I found setting classloader in ProtectionDomain in inheritedAccessControlContext to null also works, but get no idea if it will cause any problem.
```
    ClassLoader classLoader = RoleScript.getClass().getClassLoader(); // RoleScript is under the package:com.xxx.project1.script
    try {
        Vector<Class<?>> classes = (Vector<Class<?>>) org.apache.commons.lang3.reflect.FieldUtils.readDeclaredField(classLoader, "classes", true);
        for (Class<?> aClass : classes) {
            FieldUtils.writeDeclaredField(aClass.getProtectionDomain(), "classloader", null, true);
        }
    } catch (IllegalAccessException e) {
        throw new RuntimeException(e);
    }
```

Then I tried to use `ClassLoaderLeakPreventor :runCleanUps`  in this library by the following steps:
```
ClassLoaderLeakPreventorFactory factory = new ClassLoaderLeakPreventorFactory();
ClassLoaderLeakPreventor preventor = factory.newLeakPreventor(classLoader); // classLoader is a instance of ScriptClassLoader
// do the reload works
...
preventor .runCleanUps()
```
But found the metaspace size still keep increasing significantly  after each reload.

The first reload log:
```
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger error
SEVERE: Internal registry of java.beans.PropertyEditorManager not found
Oct 23, 2023 2:42:08 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFO: Releasing web app classloader from Apache Commons Logging
```
 The second and after reload log:
```
Oct 23, 2023 2:44:03 PM se.jiderhamn.classloader.leak.prevention.JULLogger error
SEVERE: Internal registry of java.beans.PropertyEditorManager not found
Oct 23, 2023 2:44:03 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFO: Releasing web app classloader from Apache Commons Logging
```
Hope there're any suggestion on this issue. Thanks!

**Comment by mjiderhamn** [comment]
Did you do `preventor.runPreClassLoaderInitiators();` **before the script classloader was used the first time** (i.e. not just before reload)?

What about the threads that are started - when are they expected to stop?

**Comment by canyuan0801** [comment]
Now I hava add `preventor.runPreClassLoaderInitiators();` before the `ScriptClassLoader` was used the first time, which was in the main thread.  But this lead to some exceptions.
The log is:
```
Oct 23, 2023 5:49:54 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFO: Initializing by loading some known offenders with leak safe classloader
// classes are loading
...
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger error
SEVERE: Internal registry of java.beans.PropertyEditorManager not found
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFO: Releasing web app classloader from Apache Commons Logging
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: JDBC driver loaded by protected ClassLoader deregistered: class com.mysql.cj.jdbc.Driver
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger error
SEVERE: Internal registry of java.beans.PropertyEditorManager not found
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Shutting down ThreadPoolExecutor of type java.util.concurrent.ScheduledThreadPoolExecutor
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Thread 'Thread[entity-call-timeout-thread,5,main]' with contextClassLoader = protected ClassLoader or child; waiting 5000 ms. Thread stack trace: 
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Shutting down ThreadPoolExecutor of type java.util.concurrent.ScheduledThreadPoolExecutor
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Thread 'Thread[notice-timeout-check-thread,5,main]' with contextClassLoader = protected ClassLoader or child; waiting 5000 ms. Thread state: RUNNABLE
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Shutting down ThreadPoolExecutor of type java.util.concurrent.ThreadPoolExecutor
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNING: Thread 'Thread[mysql-cj-abandoned-connection-cleanup,5,main]' with contextClassLoader = protected ClassLoader or child; waiting 5000 ms. Thread stack trace: 
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:150)
	at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Oct 23, 2023 5:49:55 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFO: Releasing web app classloader from Apache Commons Logging
[2023-10-23 17:49:55 INFO]GameServer:131 websocket is true. websocket open
[2023-10-23 17:49:55 INFO]HikariDataSource:80 Game - Starting...
[2023-10-23 17:49:55 ERROR]GameBootstrap:40 
java.lang.RuntimeException: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/project1
	at com.sh.game.GameContext.createGameServer(GameContext.java:103) ~[game-server-0.0.1.jar:na]
	at com.sh.game.GameBootstrap.startup(GameBootstrap.java:60) ~[game-startup-0.0.1.jar:na]
	at com.sh.game.GameBootstrap.main(GameBootstrap.java:38) ~[game-startup-0.0.1.jar:na]
Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/project1
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:325) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-3.4.5.jar:na]
	at com.sh.common.jdbc.HikariConnectionPool.<init>(HikariConnectionPool.java:27) ~[base-persist-2.0.44.1.jar:na]
	at com.sh.game.data.mysql.MysqlDataProviderProxy.<init>(MysqlDataProviderProxy.java:62) ~[game-server-0.0.1.jar:na]
	at com.sh.game.data.DataCenter.init(DataCenter.java:37) ~[game-server-0.0.1.jar:na]
	at com.sh.game.GameServer.<init>(GameServer.java:195) ~[game-server-0.0.1.jar:na]
	at com.sh.game.GameContext.createGameServer(GameContext.java:99) ~[game-server-0.0.1.jar:na]
	... 2 common frames omitted
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315) ~[na:1.8.0_371]
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106) ~[HikariCP-3.4.5.jar:na]
	... 11 common frames omitted
```
And before using the `ScriptClassLoader` to load all `script classes`,  thread pools used in the project were almost initialized by using ExecutorUtil.
```
public class ExecutorUtil {

    public static final ScheduledExecutorService COMMON_LOGIC_EXECUTOR = Executors.newScheduledThreadPool(4,
        new ThreadFactory() {
            AtomicInteger count = new AtomicInteger(0);

            @Override
            public Thread newThread(Runnable r) {
                int curCount = count.incrementAndGet();
                return new Thread(r, "common-logic-" + curCount);
            }
    });

    public static final ScheduledExecutorService EVENT_DISPATCHER_EXECUTOR = Executors.newScheduledThreadPool(4,
        new ThreadFactory() {
            AtomicInteger count = new AtomicInteger(0);

            @Override
            public Thread newThread(Runnable r) {
                int curCount = count.incrementAndGet();
                return new Thread(r, "scene-event-dispatcher-" + curCount);
            }
    });

    public static final QueueExecutor NOWHERE_EXECUTOR = new ThreadPoolExecutor("nowhere-thread", 1, 1);

  
    public static final QueueExecutor SERVER_HEART_EXECUTOR = new ThreadPoolExecutor("server-heart-thread", 1, 1);


    public static final QueueExecutor SERVER_AUTH_EXECUTOR = new ThreadPoolExecutor("server-auth-thread", 1, 1);


    public static final QueueExecutor SERVER_COMMON_EXECUTOR = new ThreadPoolExecutor("server-common-thread", 1, 1);


    public static final QueueExecutor SERVER_SOCIAL_EXECUTOR = new ThreadPoolExecutor("server-social-thread", 1, 1);


    public static final QueueExecutor PLAYER_DRIVER_EXECUTOR = new ThreadPoolExecutor("server-player-worker-thread",16,16);


    public static final QueueExecutor MAP_COMMON_EXECUTOR = new ThreadPoolExecutor("map-common-thread",1,1);

  
    public static final QueueExecutor COMMON_DRIVER_EXECUTOR = new ThreadPoolExecutor("map-worker-thread",16,16);

    public static final QueueExecutor ARENA_MATCH_EXECUTOR = new QueueExecutor("arena-match-thread", 1, 1);
}
```
So,  threads that are started shall be stopped upon the shutdown of the program.

There's a screenshot of one of the script classes:
![D XG023){1I8J2RMKM1NIS_tmb](https://github.com/mjiderhamn/classloader-leak-prevention/assets/43961413/f2768e7b-dbd4-4ed9-91a4-9cc5b1a6ab3d)

I'm not sure if these information provides any useful clues.

**Comment by canyuan0801** [comment]
The threads comes from pre-defined application thread pools, and they will stop when the application stops.

After adding `preventor.runPreClassLoaderInitiators();` before the script classloader was used the first time and each hot loading, I found that `-XX:MaxMetaspaceSize` (not `-XX:MetaspaceSize` ) must also be set to trigger gc.
In my case, set `-XX:MaxMetaspaceSize` to a appropriate value, from 164m to 180m, the metaspace size would reduce upon each hot loading.  Though each hot loading will lead to OOM but afterwhile the application worked fine.

set to 164M:
![B82}3R@RG_KY{QIAK65X97O](https://github.com/mjiderhamn/classloader-leak-prevention/assets/43961413/76ed4c4d-81e8-4342-99cf-fac9bc1cf56e)
But set `-XX:MaxMetaspaceSize` to other value finally lead to OOM and the application cannot continue.
set to 256M:
![image](https://github.com/mjiderhamn/classloader-leak-prevention/assets/43961413/f5bd35a1-eaea-4706-9213-5a5b7539d173)

It looks like to reduce the metaspace size after each hot loading there's must a gc triggered, and the gc seems has some relevance with `-XX:MaxMetaspaceSize`. But the choice of the value is really a mystery.
