### ISSUE TITLE
Spring Boot + classloader-leak-prevention-servlet3 leaks on Windows

### ISSUE THREAD

**Issue by ArloL** [mjiderhamn/classloader-leak-prevention#70]
First of all thanks a lot for your hard work creating this library. This has been a life-safer. We can properly deploy our stuff using this :)

To make sure everything works as expected we have created an integration test that checks whether our web applications can be properly undeployed: https://github.com/evosec/tomcat-classloader-leak-test

I have now found a weird reproducible issue on Windows 8 64 bit with Java 1.8.0_144 64 bit. The tests for the issue were added with the latest commit: https://github.com/evosec/tomcat-classloader-leak-test/commit/96ba5444505724ce6361453f65dbc2cd91ac9f37 The corresponding build on Linux works fine: https://travis-ci.org/evosec/tomcat-classloader-leak-test/builds/269231898

Sadly it does not work on Windows. I have attached the build log. The webapps used for testing were created using <http://start.spring.io>, change `Packaging` to `war` and `Generate`. I then added the `se.jiderhamn.classloader-leak-prevention:classloader-leak-prevention-servlet3:2.4.0` dependency.

Compare this with the plain Spring Boot application (w/o classloader-leak-prevention-servlet3) that runs just fine.

~~~
$ mvnw clean test -Dtest=de.evosec.leaktest.WebAppTestTest#testSpringBootClassLoaderLeakPreventor3_2_4_0
...
[INFO] Running de.evosec.leaktest.WebAppTestTest
Aug 28, 2017 5:22:13 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-auto-1"]
Aug 28, 2017 5:22:13 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 28, 2017 5:22:13 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Aug 28, 2017 5:22:13 PM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.5.20
Aug 28, 2017 5:22:13 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-auto-1-56972"]
Aug 28, 2017 5:22:14 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFORMATION: No global web.xml found
Aug 28, 2017 5:22:16 PM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ClassLoaderLeakPreventorListener: Settings for se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener (CL: 0x4f638935):
ClassLoaderLeakPreventorListener:   stopThreads = true
ClassLoaderLeakPreventorListener:   stopTimerThreads = true
ClassLoaderLeakPreventorListener:   executeShutdownHooks = true
ClassLoaderLeakPreventorListener:   threadWaitMs = 5000 ms
ClassLoaderLeakPreventorListener:   shutdownHookWaitMs = 10000 ms
Aug 28, 2017 5:22:16 PM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFORMATION: Initializing by loading some known offenders with leak safe classloader
Aug 28, 2017 5:22:16 PM org.apache.catalina.core.ApplicationContext log
INFORMATION: 2 Spring WebApplicationInitializers detected on classpath

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.6.RELEASE)

ClassLoaderLeakPreventorListener: se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener shutting down context by removing known leaks (CL: 0x4f638935)
javassist.CannotCompileException: by java.lang.OutOfMemoryError: Metaspace
	at javassist.ClassPool.toClass(ClassPool.java:1170)
	at javassist.CtClass.toClass(CtClass.java:1316)
	at de.evosec.leaktest.WebAppTest$4.run(WebAppTest.java:280)
Caused by: java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1183)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	... 2 more
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 129.388 s <<< FAILURE! - in de.evosec.leaktest.WebAppTestTest
[ERROR] testSpringBootClassLoaderLeakPreventor3_2_4_0(de.evosec.leaktest.WebAppTestTest)  Time elapsed: 129.341 s  <<< ERROR!
de.evosec.leaktest.WebAppTestException: ClassLoader not GC'ed
	at de.evosec.leaktest.WebAppTestTest.testSpringBootClassLoaderLeakPreventor3_2_4_0(WebAppTestTest.java:72)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition returned by method "testLeak" in class de.evosec.leaktest.WebAppTest was not fulfilled within 120 seconds.
	at de.evosec.leaktest.WebAppTestTest.testSpringBootClassLoaderLeakPreventor3_2_4_0(WebAppTestTest.java:72)
...
~~~

~~~
$ mvnw clean test -Dtest=de.evosec.leaktest.WebAppTestTest#testSpringBoot
...
[INFO] Running de.evosec.leaktest.WebAppTestTest
Aug 28, 2017 5:24:39 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-auto-1"]
Aug 28, 2017 5:24:39 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 28, 2017 5:24:39 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Aug 28, 2017 5:24:39 PM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.5.20
Aug 28, 2017 5:24:39 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-auto-1-57092"]
Aug 28, 2017 5:24:40 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFORMATION: No global web.xml found
Aug 28, 2017 5:24:42 PM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Aug 28, 2017 5:24:43 PM org.apache.catalina.core.ApplicationContext log
INFORMATION: 2 Spring WebApplicationInitializers detected on classpath

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.6.RELEASE)

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.008 s - in de.evosec.leaktest.WebAppTestTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
...
~~~

**Comment by ArloL** [comment]
I have continued my debugging and now found that it is not because of the platform but because of the JDK version. JDK 1.8.0_131 works fine. JDK 1.8.0_141 and _144 do not.

**Comment by ArloL** [comment]
I will re-open this with a better description.
