### ISSUE TITLE
classloader-leak-preventor-servlet3 on JDK > 8u141 leaks

### ISSUE THREAD

**Issue by ArloL** [mjiderhamn/classloader-leak-prevention#71]
First of all thanks a lot for your hard work creating this library. This has been a life-safer. We can properly deploy our stuff using this :)

To make sure everything works as expected we have created an integration test that checks whether our web applications can be properly undeployed: https://github.com/evosec/tomcat-classloader-leak-test

I have now found a reproducible issue with Oracle JDK >= 1.8.0_141 (64 bit). The webapp I use was built from https://github.com/ArloL/jdk8u144-classloader-leak-demo-webapp

All the tests with a webapp that includes the classloader-leak-preventor-servlet (with and without 3) fail all the time:
~~~
$ set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
$ mvnw clean test -Dtest=de.evosec.leaktest.WebAppTestTest#testWebappClassLoaderLeakPreventor3_2_4_0
...
[INFO] Running de.evosec.leaktest.WebAppTestTest
Aug 29, 2017 9:00:23 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-auto-1"]
Aug 29, 2017 9:00:23 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 29, 2017 9:00:23 AM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Aug 29, 2017 9:00:23 AM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.5.20
Aug 29, 2017 9:00:23 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-auto-1-57403"]
Aug 29, 2017 9:00:23 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFORMATION: No global web.xml found
Aug 29, 2017 9:00:24 AM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ClassLoaderLeakPreventorListener: Settings for se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener (CL: 0x4461c7e3):
ClassLoaderLeakPreventorListener:   stopThreads = true
ClassLoaderLeakPreventorListener:   stopTimerThreads = true
ClassLoaderLeakPreventorListener:   executeShutdownHooks = true
ClassLoaderLeakPreventorListener:   threadWaitMs = 5000 ms
ClassLoaderLeakPreventorListener:   shutdownHookWaitMs = 10000 ms
Aug 29, 2017 9:00:24 AM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFORMATION: Initializing by loading some known offenders with leak safe classloader
ClassLoaderLeakPreventorListener: se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener shutting down context by removing known leaks (CL: 0x4461c7e3)
Aug 29, 2017 9:00:25 AM se.jiderhamn.classloader.leak.prevention.JULLogger error
SCHWERWIEGEND: Internal registry of java.beans.PropertyEditorManager not found
Aug 29, 2017 9:00:25 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-nio-auto-1-57403"]
Aug 29, 2017 9:00:25 AM org.apache.catalina.core.StandardService stopInternal
INFORMATION: Stopping service [Tomcat]
Aug 29, 2017 9:00:25 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-nio-auto-1-57403"]
Aug 29, 2017 9:00:25 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-nio-auto-1-57403"]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.83 s - in de.evosec.leaktest.WebAppTestTest
...
~~~

vs.

~~~
$ set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_141
$ mvnw clean test -Dtest=de.evosec.leaktest.WebAppTestTest#testWebappClassLoaderLeakPreventor3_2_4_0
...
[INFO] Running de.evosec.leaktest.WebAppTestTest
Aug 29, 2017 8:57:46 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-auto-1"]
Aug 29, 2017 8:57:46 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 29, 2017 8:57:46 AM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Aug 29, 2017 8:57:46 AM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.5.20
Aug 29, 2017 8:57:46 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-auto-1-57318"]
Aug 29, 2017 8:57:46 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFORMATION: No global web.xml found
Aug 29, 2017 8:57:47 AM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ClassLoaderLeakPreventorListener: Settings for se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener (CL: 0x58134517):
ClassLoaderLeakPreventorListener:   stopThreads = true
ClassLoaderLeakPreventorListener:   stopTimerThreads = true
ClassLoaderLeakPreventorListener:   executeShutdownHooks = true
ClassLoaderLeakPreventorListener:   threadWaitMs = 5000 ms
ClassLoaderLeakPreventorListener:   shutdownHookWaitMs = 10000 ms
Aug 29, 2017 8:57:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFORMATION: Initializing by loading some known offenders with leak safe classloader
ClassLoaderLeakPreventorListener: se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener shutting down context by removing known leaks (CL: 0x58134517)
Aug 29, 2017 8:57:48 AM se.jiderhamn.classloader.leak.prevention.JULLogger error
SCHWERWIEGEND: Internal registry of java.beans.PropertyEditorManager not found
javassist.CannotCompileException: by java.lang.OutOfMemoryError: Metaspace
	at javassist.ClassPool.toClass(ClassPool.java:1170)
	at javassist.CtClass.toClass(CtClass.java:1316)
	at de.evosec.leaktest.WebAppTest$4.run(WebAppTest.java:280)
Caused by: java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1183)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	... 2 more
Aug 29, 2017 8:59:48 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-nio-auto-1-57318"]
Aug 29, 2017 8:59:48 AM org.apache.catalina.core.StandardService stopInternal
INFORMATION: Stopping service [Tomcat]
Aug 29, 2017 8:59:48 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-nio-auto-1-57318"]
Aug 29, 2017 8:59:48 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-nio-auto-1-57318"]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 122.924 s <<< FAILURE! - in de.evosec.leaktest.WebAppTestTest
[ERROR] testWebappClassLoaderLeakPreventor3_2_4_0(de.evosec.leaktest.WebAppTestTest)  Time elapsed: 122.877 s  <<< ERROR!
de.evosec.leaktest.WebAppTestException: ClassLoader not GC'ed
	at de.evosec.leaktest.WebAppTestTest.testWebappClassLoaderLeakPreventor3_2_4_0(WebAppTestTest.java:87)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition returned by method "testLeak" in class de.evosec.leaktest.WebAppTest was not fulfilled within 120 seconds.
	at de.evosec.leaktest.WebAppTestTest.testWebappClassLoaderLeakPreventor3_2_4_0(WebAppTestTest.java:87)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   WebAppTestTest.testWebappClassLoaderLeakPreventor3_2_4_0:87 � WebAppTest Class...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
...
~~~

**Comment by mjiderhamn** [comment]
@ArloL Would it be possible for you to provide a heap dump that I can analyze, in order to save time reproducing this myself? Since you are getting `java.lang.OutOfMemoryError` you should be able to easily get a dump using `-XX:+HeapDumpOnOutOfMemoryError`.

**Comment by ArloL** [comment]
I have uploaded a zipped heap dump here: https://www.evosec.de/java_pid9076.zip

**Comment by mjiderhamn** [comment]
Indeed this seems to be something added to recent Java versions. I'm currently working on a fix.
![Path to GC root](https://user-images.githubusercontent.com/837073/30132194-dcb6f6fe-934f-11e7-81cb-e8e24ab52910.jpg)

**Comment by mjiderhamn** [comment]
@ArloL Could you compile the library from the latest sources and check whether my changes resolve the issue?

**Comment by ArloL** [comment]
It works 👍 

~~~
$ set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_141
$ mvnw clean test -Dtest=de.evosec.leaktest.WebAppTestTest#testWebappClassLoaderLeakPreventor3_2_4_1_SNAPSHOT
[INFO] Running de.evosec.leaktest.WebAppTestTest
Sep 07, 2017 10:00:45 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-auto-1"]
Sep 07, 2017 10:00:45 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Sep 07, 2017 10:00:45 AM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Tomcat]
Sep 07, 2017 10:00:45 AM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.5.20
Sep 07, 2017 10:00:45 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-auto-1-59735"]
Sep 07, 2017 10:00:45 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFORMATION: No global web.xml found
Sep 07, 2017 10:00:46 AM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that
were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ClassLoaderLeakPreventorListener: Settings for se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener (CL: 0x226a82c4):
ClassLoaderLeakPreventorListener:   stopThreads = true
ClassLoaderLeakPreventorListener:   stopTimerThreads = true
ClassLoaderLeakPreventorListener:   executeShutdownHooks = true
ClassLoaderLeakPreventorListener:   threadWaitMs = 5000 ms
ClassLoaderLeakPreventorListener:   shutdownHookWaitMs = 10000 ms
Sep 07, 2017 10:00:46 AM se.jiderhamn.classloader.leak.prevention.JULLogger info
INFORMATION: Initializing by loading some known offenders with leak safe classloader
ClassLoaderLeakPreventorListener: se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener shutting down context by removing kn
own leaks (CL: 0x226a82c4)
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger warn
WARNUNG: AccessControlContext of javax.imageio.spi.IIORegistry used custom combiner - unsetting
Sep 07, 2017 10:00:47 AM se.jiderhamn.classloader.leak.prevention.JULLogger error
SCHWERWIEGEND: Internal registry of java.beans.PropertyEditorManager not found
Sep 07, 2017 10:00:47 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-nio-auto-1-59735"]
Sep 07, 2017 10:00:47 AM org.apache.catalina.core.StandardService stopInternal
INFORMATION: Stopping service [Tomcat]
Sep 07, 2017 10:00:47 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-nio-auto-1-59735"]
Sep 07, 2017 10:00:47 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-nio-auto-1-59735"]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.93 s - in de.evosec.leaktest.WebAppTestTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
~~~

**Comment by seamusmac** [comment]
@mjiderhamn Thanks for your awesome library. I am just after finding this exact same issue. Matched up with MAT and a HPROF dump. Wondering when this fix will get released into the wild?

**Comment by mjiderhamn** [comment]
Version 2.5.0 is on its way to Maven Central now! :-)
